apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: mytg
spec:
  replicas: 5
  selector:
    matchLabels:
     env: stage
  template:
    metadata:
     labels:
       env: stage
    spec:
     imagePullSecrets:
       - name: passwd-for-docker-hub
     containers:
       - name: tomcat
         image:  cdtsbikaner/devops150624:BUILD_NUMBER
         ports:
          - containerPort: 8080
